-- Seed de horarios médicos
INSERT INTO "HorarioMedico" (
        "usuarioId",
        "especialidad",
        "diaSemana",
        "horaInicio",
        "horaFin",
        "capacidadPorDia",
        "activo",
        "createdAt",
        "updatedAt"
    )
VALUES (
        1,
        'Medicina Interna',
        1,
        '08:00',
        '12:00',
        10,
        true,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        1,
        'Medicina Interna',
        3,
        '08:00',
        '12:00',
        10,
        true,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        2,
        'Pediatría',
        2,
        '09:00',
        '13:00',
        8,
        true,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        2,
        'Pediatría',
        4,
        '09:00',
        '13:00',
        8,
        true,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        1,
        'Medicina Interna',
        5,
        '08:00',
        '12:00',
        10,
        true,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        2,
        'Pediatría',
        5,
        '09:00',
        '13:00',
        8,
        true,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    );